# Site settings
title: Comicgram
description: Un newsletter mensual con la información más relevante del mundo de los cómics, datos curiosos, información de los personajes y reseñas de las películas
url: "http://comicgram.io" # the base hostname & protocol for your site
twitter_username: adrrian17
github_username:  adrrian17

# Build settings
markdown: kramdown
port: 3000
